### ISSUE TITLE
Objective-C support

### ISSUE THREAD

**Issue by hdoria** [TakeScoop/SwiftyRSA#1]
How can I use this on my Objective-C project?

**Comment by ldiqual** [comment]
@hdoria Thanks for your input! I added objective-c support to SwiftyRSA. Code example is available here: https://github.com/TakeScoop/SwiftyRSA#use-with-objective-c. You can also take a look at the following objc tests: https://github.com/TakeScoop/SwiftyRSA/blob/master/SwiftyRSATests/SwiftyRSAObjcTests.m

Let me know if you have any issue.

**Comment by hdoria** [comment]
Awesome! Thanks you a lot.
