### ISSUE TITLE
Simplify data for key reference method implementation

### ISSUE THREAD

**Issue by ianbytchek** [TakeScoop/SwiftyRSA#103]
👋 Hello and thanks for awesome work, it's fantastic! While trying to find a workaround for `SecKeyCopyExternalRepresentation` on older systems I noticed how you `SecItemAdd` than `SecItemDelete` in:
https://github.com/TakeScoop/SwiftyRSA/blob/1cb6b880d82aa13a424def36af21f11ec0aca707/SwiftyRSA/SwiftyRSA.swift#L84-L123

You can achieve the same with just `SecItemExport`, like [here](https://github.com/tbfly/Hacking.and.Securing.iOS.Applications_Source_Code/blob/b5394cc494be14402c003c1a1411559a5d751ea3/ch10/pkicrypt.m). Question is, is there any reason why you took current approach over that?

**Comment by ldiqual** [comment]
@ianbytchek That's a great question! I believe that `SecItemExport` is not available on iOS, which is the primary target for SwiftyRSA. According to the docs it's only available on macOS 10.7+ https://developer.apple.com/documentation/security/1394828-secitemexport. Let me know if I'm missing something. Closing for now
