### ISSUE TITLE
Crash due to hashValue implementation on CFString

### ISSUE THREAD

**Issue by flockoffiles** [TakeScoop/SwiftyRSA#107]
We have a crash due to the presence of implementation of hashValue method in SwiftyRSA.swift, even if no other methods of SwiftyRSA get used by an app.

There is a fix/work-around if you implement the hashValue method like this:

```    
    public var hashValue: Int {
        // So, this does NOT work: 
        // return (self as String).hashValue
        // But this DOES:
        return (self as NSString).hashValue
    }

```

I don't know if that's an Apple bug, but using the hashValue implementation from the Swift String (instead of NSString) seems to mess up things completely.

To reproduce the crash you need to create an empty app with a simple framework inside.
Create a test function which creates a dictionary and place that function in the simple framework as well (name it differently). Then, first call the function located in the main app, then the one located in the framework. You will get an exception in the second call.

```
// In our test framework we call this function testDictionaryFramework()
func testDictionary() {
    let sizeInBits = 2160
    let keyClass = kSecAttrKeyClassPublic
    let keyDict: [CFString: Any] = [
        kSecAttrKeyType: kSecAttrKeyTypeRSA,
        kSecAttrKeyClass: keyClass,
        kSecAttrKeySizeInBits: NSNumber(value: sizeInBits),
        kSecReturnPersistentRef: true
    ]
    
    keyDict.forEach { (key: CFString, value: Any) in
        print("Key: \(key), Value: \(value)")
    }
    
    let nsDict = keyDict as NSDictionary
    nsDict.forEach { (key: Any, value: Any) in
        print("Key: \(key), Value: \(value)")
    }
}

```

We have a test project that reproduces the crash. Please contact me if you need it if you want to explore it further.

**Comment by flockoffiles** [comment]
Test project:
https://wetransfer.com/downloads/88b733eb73bde35910777b699aebd1e820180309174835/59302b5f58bf06f5a8d9bb18fada3a6520180309174835/f2cd84

**Comment by ldiqual** [comment]
@flockoffiles I was unable to reproduce the issue, but after looking into the hashable extension I realized it was no longer needed for the code to compile. I'll be removing it in https://github.com/TakeScoop/SwiftyRSA/pull/125
