### ISSUE TITLE
Getting `asn1ParsingFailed` error when creating key

### ISSUE THREAD

**Issue by shashak005** [TakeScoop/SwiftyRSA#108]
I am getting asn1ParsingFailed this error

**Comment by 4taras4** [comment]
the same

**Comment by ldiqual** [comment]
@shashak005 @4taras4 Thanks for opening an issue!

This error most likely means that the key data you're providing is not a valid ASN1 key. Make sure you're using a proper PEM or DER key and [call the appropriate initializer](https://github.com/TakeScoop/SwiftyRSA#advanced-usage) depending on the key type.

The only way I can help you analyze the error is if you provide the key file content or string here (don't share your private keys though) and the exact code used to initialize the SwiftyRSA public/private key.

**Comment by ericoda** [comment]
@ldiqual Thanks for your info. I got the same error when trying to use the "der" key, the encryption works on "pem" key though. I made "der" key by following commands:
```
openssl req -new -key private_key.pem -out rsaCerReq.csr
openssl x509 -req -days 3650 -in rsaCerReq.csr -signkey private_key.pem -out rsaCert.crt
openssl x509 -outform der -in rsaCert.crt -out public_key.der
```

I create rsa keys on the website "http://web.chacuo.net/netrsakeypair", by choosing the "pkcs1" format without password for the certificate.

My public key is 
```-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmBrOqqED8vF+zQnvJ6PCJ4oXu
IJHpv2DNs2NQVyk6SMSk+XPgPoZzmWbScIyUKiigyx0+Oc0+uQ3yCuvaWqH28+2T
Fu8vkk6a/f4EMT+F7Npvxmdqtp2lxNwFYiK0/R2JDJnQ/XJxr260GvyjGfAx1LIM
xOiCHL4hXtYi57MSEQIDAQAB
-----END PUBLIC KEY-----```

I will appreciate your help.

**Comment by ldiqual** [comment]
@ericoda Sorry for the delay on this. SwiftyRSA doesn't support certificates, only public keys + private keys. You can generate those keys using [this method](https://github.com/TakeScoop/SwiftyRSA#create-public-and-private-rsa-keys) in the documentation, or by [generating them from code](https://github.com/TakeScoop/SwiftyRSA#create-a-publicprivate-rsa-key-pair).

If you have issues parsing actual keys, please re-open an issue. Thank you!

**Comment by Venaseph** [comment]
I've run into the same problem. Any suggestions on how I can parse the actual public key from my supplied certificate? Thanks ahead of time.
