### ISSUE TITLE
Generating RSA key pair on iOS

### ISSUE THREAD

**Issue by Laban1** [TakeScoop/SwiftyRSA#11]
Thanks for writing this useful library!

Can this library be used to generate an RSA key pair on the iOS device (as opposed to generating the keys on a server)?  If not, any suggestion on another library that will generate PEM keys that are compatible with this library?

**Comment by quentinlesceller** [comment]
Hi Laban1,

Currently this library cannot be used to generate an RSA keypair. We might implement this function later.

For now, to generate the keys, you can use [AsymmetricCryptoManager](https://github.com/DigitalLeaves/AsymmetricCrypto). It should work perfectly with SwiftyRSA.

For example, you can try something like this, generate a keypair and sign data with the private key (don't forget to change the scope of getPublicKeyReference() and getPrivateKeyReference() in AsymmetricCryptoManager):
```
AsymmetricCryptoManager.sharedInstance.createSecureKeyPair({ (success, error) in
    if success {
        let privateKeyRef = AsymmetricCryptoManager.sharedInstance.getPrivateKeyReference() 

        let bytes = [UInt32](count: 2048, repeatedValue: 0).map { _ in arc4random() }
        let data = NSData(bytes: bytes, length: bytes.count * sizeof(UInt32))
        
        let signature = try! SwiftyRSA.signData(data, privateKey: privateKeyRef )
    }
})
```
Feel free to ask me anything about this. You can also look at one of my previous project, [Puzzlr](https://github.com/quentinlesceller/Puzzlr/), where I used end-to-end encryption with SwiftyRSA.

**Comment by quentinlesceller** [comment]
Also, if you wan to generate a PEM public key, you can use [CryptoExportImportManager](https://github.com/DigitalLeaves/CryptoExportImportManager) like this :
```
AsymmetricCryptoManager.sharedInstance.createSecureKeyPair({ (success, error) in
    if success {
        let cryptoImportExportManager = CryptoExportImportManager()
        
        let publicKeyData = AsymmetricCryptoManager.sharedInstance.getPublicKeyData()
        let publicKeyPEM = cryptoImportExportManager.exportRSAPublicKeyToPEM(publicKeyData!, keyType: kSecAttrKeyTypeRSA as String, keySize: 2048)

        print(publicKeyPEM)
    }
})
```

**Comment by Laban1** [comment]
Hi quentinlesceller,

First off, thanks for your helpful reply!

I started trying out your suggestions, but came across some questions.  Getting the public key in PEM format works great (including using it on the server to encrypt data), but how do I persist the private key on the iPad (I seem to only be able to get a _reference_ to the key)?

    AsymmetricCryptoManager.sharedInstance.createSecureKeyPair({ (success, error) in
       if success {
          let cryptoImportExportManager = CryptoExportImportManager()
          let publicKeyData = AsymmetricCryptoManager.sharedInstance.getPublicKeyData()
          let publicKeyPEM = cryptoImportExportManager.exportRSAPublicKeyToPEM(publicKeyData!, keyType: kSecAttrKeyTypeRSA as String, keySize: 2048)
          print(publicKeyPEM)
                
          let privateKeyRef = AsymmetricCryptoManager.sharedInstance.getPrivateKeyReference()
          // Here: I need to save the private key (preferably in PEM format, but not required) in the keychain
          // so that I can use it to encrypt some strings later.
       }
    })

Here is the specific scenario that I am trying to address:
1) The server calls the iPad, requesting that the iPad creates a key pair and returns the public key in PEM format.
2) The iPad creates the key pair and stores the private key in the key chain + returns the public key to the server.
3) The server encrypts a sensitive string with the iPad's public key and Base64 encodes the encrypted string.
4) The server makes another call to the iPad with the encrypted string
5) The iPad reads the private key from the key chain and decrypts string (after decoding the Base64, if this is needed).

Perhaps you can guide me a bit further on this?

**Comment by paulw11** [comment]
The library is already creating the key pair and storing it in the keychain, so any time you want the private key you can simply say `let privateKeyRef = AsymmetricCryptoManager.sharedInstance.getPrivateKeyReference()`

**Comment by quentinlesceller** [comment]
+1 @paulw11. Until you delete the keypair, keys are stored in the keychain (under the tag "com.AsymmetricCrypto.keypair" in the case of AsymmetricCryptoManager).

**Comment by Laban1** [comment]
@paulw11 Thanks, it works fine now!  

Yes, I am aware that this is not a perfect solution and I have not been able to find an iOS web server with SSL support.  The data is somewhat sensitive, but not overly so and it does not have much value for an attacker (and both the server and the iPads are on a private network with other security measures in place).  

Having said the above, I would still be very interested in suggestions for improvements to my scenario!

**Comment by quentinlesceller** [comment]
Why not storing the server public key on the iPad (basically recreate SSL)?
1) The server calls the iPad, requesting that the iPad creates a key pair and returns the public key in PEM format.
2) The iPad creates the key pair and stores the private key in the key chain + returns the public key encrypted with the server public key to the server.
3) The server encrypts and sign a sensitive string with the iPad's public key and Base64 encodes the encrypted string.
...

**Comment by Laban1** [comment]
@quentinlesceller Actually, I already have the server public key on the iPads (for sending sensitive stuff from the iPads to the server).  

I can see how using SSL with an official, trusted certificate or using host keys can help to safeguard against MITM, etc., but how will encrypting the iPad's public key will add to the security?  In other words, what vulnerability does it address?

**Comment by Laban1** [comment]
Hi @quentinlesceller, I am coming across an issue when creating a key pair - the generated keys are always the same.  Here is my code:

	AsymmetricCryptoManager.sharedInstance.createSecureKeyPair({ (success, error) in
		if success {
			let cryptoImportExportManager = CryptoExportImportManager()
			let publicKeyData = AsymmetricCryptoManager.sharedInstance.getPublicKeyData()
			var publicKeyPem = cryptoImportExportManager.exportRSAPublicKeyToPEM(publicKeyData!, keyType: kSecAttrKeyTypeRSA as String, keySize: 2048)
			
			print(publicKeyPem)
		}
	})

publicKeyPem is always:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxMVZqzfWXpB3tUfB0RGV
iqGY6GF8IqXPakzuiA92NPfZrqrixE4TERoEK3uV6jrtxEsa4fdVMh9Bzk6FGjOJ
Ix0mPsT79g22v8GLZes/DoC8sNy4rX726b9wTeeT/l/vYJ3xXaSNxDgO+a380IXp
p8DOdwquQoWVxGCVYvMRZNEFqiNFICbUpPIBJafhbFjsCPUtOYm95VCIc6Ixk3kR
VRck7HWkky8gIB2D0+ZaCO0dRNls9aPDfo4Hll/59YpERKdkbTNnRUACY2EltYfH
JG52WrVYbIISXS1YUEVRNoDHwVCjDcdj2QGPRdkACw78LrwCotn+ZhtVag9uZHpp
qwIDAQAB
-----END PUBLIC KEY-----

What am I missing?

**Comment by quentinlesceller** [comment]
@Laban1 My mistake, there is no point at encrypting the public key. 
Basically you want mutual authentication or at least one-way authentication (client knows that he is communicating with the server).

For now, I can see two ways for you to exchange data securely between the server and the iPad. In both cases, the iPad needs to know the server public key beforehand.
* You can stick with your protocol but messages need at least to be signed. This is still vulnerable to a MITM attack where the attacker intercept the first message (iPad public key) and replace it with his but it is not vulnerable to a Server Impersonation:
    1. The server calls the iPad, requesting that the iPad creates a RSA keypair.
    2. The iPad creates the keypair and stores the keys in the keychain. Then, he returns the public key to the server.
    3. The server encrypts a sensitive string with the iPad's public key and **sign** the message with his private key.
    4. The server makes another call to the iPad with the encrypted string
    5. The iPad verify the message signature and if it is correct, decrypts the string with his private key.


* The second method is something close to OpenSSL with RSA as Key Transport algorithm and is more suited for long messages since the encryption here is faster.
    1. The iPad generates and send a symmetric key to the server, encrypted with the server Public Key.
    2. The server answer with a simple AES encrypted "hello". 
    3. iPad checks the message if it correspond to the previous "hello".
    4. Server and iPad can now communicate using the previous key with a symmetric key algorithm and MAC (MAC then Encrypt).
    5. At the end of the session, symmetric key should be deleted.

**Comment by quentinlesceller** [comment]
@Laban1 Did you delete the keypair before creating a new one ?

**Comment by Laban1** [comment]
@quentinlesceller Yes, but perhaps not correctly: 

`Keychain.removeValue(forKey: "com.AsymmetricCrypto.keypair")`

**Comment by Laban1** [comment]
@quentinlesceller, re. the security, yes implementing signing is a good idea.   

Re. the key generation, I just noticed that you have a deleteSecureKeyPair in AsymmetricCryptoManager and when calling it before calling createSecureKeyPair, it the key generation works fine (different keys every time).  Note: just a suggestion: it might may sense for createSecureKeyPair to automatically delete the existing key pair (since if you explicitly call createSecureKeyPair it is very unlikely that you want to keep the old key pair. 

Thanks again for all your help.

**Comment by quentinlesceller** [comment]
Glad that everything worked !
Indeed, you need to verify that there is no keypair under this tag in the keychain before creating a new one. 
In AsymmetricCryptoManager, the author used something like this.
```
if keyPairExists { // delete current key pair
    AsymmetricCryptoManager.sharedInstance.deleteSecureKeyPair({ (success) -> Void in
        if success {
            print("Keypair successfully deleted")
            self.keyPairExists = false
        } else {
            print("Error deleting keypair.") 
        }
    })
} else { // generate keypair
    AsymmetricCryptoManager.sharedInstance.createSecureKeyPair({ (success, error) -> Void in
        if success {
            print("RSA-2048 keypair successfully generated.")
            self.keyPairExists = true
        } else { 
            print("An error happened while generating a keypair: \(error)")
        }
    })
}
```
