### ISSUE TITLE
Use of unresolved identifier 'dateArray'?

### ISSUE THREAD

**Issue by richierockskool** [TakeScoop/SwiftyRSA#113]
// I have defined the var dateArray, but it is pulling this error on dateArray, what am I doing wrong?
xcode 9.3 swift 3.0

var dateArray: Array<String> = Array()
                            var dayNumber = 0
                            var readingNumber = 0
                            
                            if let weatherArray = jsonObj!.value(forKey: "list") as? NSArray {
                                for dict in weatherArray {
                                    if let weatherDictionary = (dict as! NSDictionary).value(forKey: "list") as? NSDictionary {
                                        if let date = weatherDictionary.value(forKey: "dt_txt") as? String {
                                            
                                            if readingNumber == 0 {
                                                dateArray.append(date)
                                            } else if date > dateArray[dayNumber] {
                                                dateArray[dayNumber] = date
                                            }
                                            
                                        }
                                        
                                    } else {
                                        print("Error: unable to find date in dictionary")
                                    }
                                
                                    
                                    readingNumber += 1
                                    if readingNumber == 8 {
                                        readingNumber = 0
                                        dayNumber += 1
                                        
                                        
                                    }
                                }
                            }
                        }
                    }
                    
                }
            }
   
            func formatDate(date: NSDate) -> String {
                let dateFormatter = DateFormatter()
                dateFormatter.dateStyle = .medium
                return dateFormatter.string(from: date as Date)
                
                
                DispatchQueue.main.async {
                    self.dateLabel1.text = ": \(formatDate(date: dateArray[0]))"
                    self.dateLabel2.text = ": \(formatDate(date: dateArray[1]))"
                    self.dateLabel3.text = ": \(formatDate(date: dateArray[2]))"
                    self.dateLabel4.text = ": \(formatDate(date: dateArray[3]))"
                    self.dateLabel5.text = ": \(formatDate(date: dateArray[4]))"

**Comment by ldiqual** [comment]
@richierockskool Thanks for opening an issue. Are you sure this is related to SwiftyRSA? I don't see any crypto-related code in here.

**Comment by ldiqual** [comment]
Closing because unrelated to SwiftyRSA
