### ISSUE TITLE
pemFileNotFound("ABCD")

### ISSUE THREAD

**Issue by shafeerp** [TakeScoop/SwiftyRSA#119]
Hi ,
When i try to use swiftyrsa in my Cocoa touch framework i'm getting pemFileNotFound("ABCD") error .. can you help me to resolve this

**Comment by gigallo** [comment]
Same problem here when i try to do:
 try publicKey = try PublicKey(pemNamed: "Keys/publickey", in: Bundle.main)

**Comment by ldiqual** [comment]
@shafeerp How is `ABCD` added to your project? Make sure it's copied inside your bundle

@gigallo The `pemNamed` constructor unfortunately doesn't support subdirectories, but you can use something like [this](https://developer.apple.com/documentation/foundation/bundle/1409670-path?changes=_2):

```
let path = Bundle.main.path(forResource: "publickey", ofType: "pem", inDirectory: "Keys")
let keyString = try String(contentsOf: URL(fileURLWithPath: path), encoding: .utf8)
let key = PublicKey(pemEncoded: keyString)
```

**Comment by shafeerp** [comment]
@ldiqual Thanks for your support , my problem is resolved . I have done it in below format

let publicKey = try PublicKey(pemNamed: "ABCD", in: Bundle(for: Verify.self))
