### ISSUE TITLE
SHA2 support for digests / signatures?

### ISSUE THREAD

**Issue by Laban1** [TakeScoop/SwiftyRSA#12]
Any plans to add support for SHA2 for message digests / signatures?

**Comment by paulw11** [comment]
Good idea.  I have created a pull request to add this, but you can try it out here - https://github.com/paulw11/SwiftyRSA in the mean time.

**Comment by Laban1** [comment]
What took you so long? :-)   Thanks!!

**Comment by paulw11** [comment]
This feature is now in the repository
