### ISSUE TITLE
getting error chunkDecryptFailed(0)

### ISSUE THREAD

**Issue by qadirsuh** [TakeScoop/SwiftyRSA#127]
Hi there. 
I am trying to decrypt some message with my private key using this (SwiftyRSA awesome library). I am getting error 
> chunkDecryptFailed(0)

Here is my iOS swift code. Any clue?

                    ```
                        if (Code == "200") {
                        let control = rawJson["LL"]["control"].stringValue
                        if(control.contains("jdev/sys/keyexchange")){
                            self.exchangeKeyValue = rawJson["LL"]["value"][].stringValue
                            let ciphertext_replace_n = exchangeKeyValue.replacingOccurrences(of: "\n", with: "")
                            let ciphertext_base64 = ciphertext_replace_n.toBase64()!;
                                                       
                            do {
                                
                                let privateKey = try PrivateKey(pemEncoded: self.privateKey)
                                print("privateKey", privateKey)
                                let encrypted = try EncryptedMessage(base64Encoded: ciphertext_base64)
                                print("encrypted", encrypted)
                                let clear = try encrypted.decrypted(with: privateKey, padding: .PKCS1)

                                let data = clear.data
                                let base64String = clear.base64String
                                let string = try clear.string(encoding: .utf8)

                                print("data", data)
                                print("base64String", base64String)
                                print("string", string)

                            }catch{
                                print("decrypt errror", error);
                            }
                        }
                    }

```

**Details**

 - Version of SwiftyRSA in Podfile => pod 'SwiftyJSON', '~> 4.0'
 - Exact code that you're using to create the key / message / signature
actually I am using following the docs of Loxone miniserver
https://www.loxone.com/dede/wp-content/uploads/sites/2/2016/08/0903_Communicating-with-the-Miniserver.pdf => _Page 5 of 21_ 
 - The full description of the error (`error.localizedDescription`)
> chunkDecryptFailed(0)

**Comment by ldiqual** [comment]
@qadirsuh Thanks for opening an issue! Have you tried using different kinds of padding for the decryption?

**Comment by pltlg** [comment]
@ldiqual  I tried and it does not work. If I try with different padding (for example MD5 or PKCS1MD2) throws a chunkEncryptFailed(index: 0) error.

chunkDecryptFailed error in case of PKCS1 padding: 
` 
let x = encrypt(text: "clear text")
let c = decrypt(data: x.data) // -> chunkDecryptFailed(index: 0)

func encrypt(text: String) -> (base64String: String, data: Data)? {
        do{
            let serverPublicKey = "xxx"
            let publicKey = try PublicKey(pemEncoded: serverPublicKey)
            let clear = try ClearMessage(string: "Clear Text", using: .utf8)
            let encrypted = try clear.encrypted(with: publicKey, padding: .PKCS1)
            let base64String = encrypted.base64String
            return (base64String: encrypted.base64String, data: encrypted.data)
        } catch {
            print(error)
            return nil
        }
    }
    
    func dencrypt(data: Data) -> String? {
        do{
            let serverPrivateKey = "xxx"
            let privateKey = try PrivateKey(pemEncoded: serverPrivateKey)
            let encrypted = try EncryptedMessage(data: data)
            let clear = try encrypted.decrypted(with: privateKey, padding: .PKCS1) // error throws here
            let string = try clear.string(encoding: .utf8)
            return string
        } catch {
            print(error) //chunkDecryptFailed(index: 0)
            return nil
        }
    }
`

**Comment by mehulmodihb** [comment]
Hello, I am facing same issue. when i try to decrypt any message or key I am getting exception for  chunkDecryptFailed(0)

**Comment by tushar666** [comment]
Hi 
Padding = .PKCS1
Description = The operation couldn’t be completed. (SwiftyRSA.SwiftyRSAError error 5.)
Error =   chunkDecryptFailed(index: 0)

**Comment by chanindev** [comment]
> Hi
> Padding = .PKCS1
> Description = The operation couldn’t be completed. (SwiftyRSA.SwiftyRSAError error 5.)
> Error = chunkDecryptFailed(index: 0)
> 
> Sometimes it works and sometimes it don't.

My issue is the same. I solved it by updating SwiftyRSA version to 1.6.0.

**Comment by jacabodam** [comment]
Hello, I have the same issue, I am using SwiftyRSA version 1.7.0
Error:Couldn't decrypt chunk at index 0

**Comment by codeHorizonVentures** [comment]
version 1.8.0 same issue

**chunkDecryptFailed(index: 0)**

> try encrypted.decrypted(with: privateKey, padding: .PKCS1)
