### ISSUE TITLE
Xcode10 Build Failed

### ISSUE THREAD

**Issue by caixianghui-s** [TakeScoop/SwiftyRSA#134]
![wechatimg29](https://user-images.githubusercontent.com/42334861/45739844-773bff80-bc26-11e8-8fc9-7a504d8ef0b7.jpeg)

**Comment by wanght** [comment]
manually change to
let range: Range<String.Index> = start..<end
and waiting for update .....

**Comment by danurna** [comment]
Had the same issue and just updated to version 1.5.0 [0], which solves that problem. 
[0] https://github.com/TakeScoop/SwiftyRSA/releases/tag/1.5.0

**Comment by alizainprasla** [comment]
having same issue in **XCode 11** with pod **'SwiftyRSA' , '1.4.0'**

**Comment by alizainprasla** [comment]
> Had the same issue and just updated to version 1.5.0 [0], which solves that problem.
> [0] https://github.com/TakeScoop/SwiftyRSA/releases/tag/1.5.0

Any solution?

**Comment by danurna** [comment]
@alizainprasla just use `pod 'SwiftyRSA' , '1.5.0'`

**Comment by ldiqual** [comment]
@danurna is right, 1.5.0 brings Xcode 10 support and you can use this from now on. Thanks!
