### ISSUE TITLE
SHA2 digests not included when using Carthage

### ISSUE THREAD

**Issue by jb431** [TakeScoop/SwiftyRSA#15]
I am interested in the new SHA2 digests and I just did a Carthage update to try it out, but I do not see the new overloads for verifySignatureString (with the optional DigestType argument).

In my Cartfile, I only have this (no version restriction):

    github "TakeScoop/SwiftyRSA"

My Cartfile.resolved shows that it is still using version 0.3.0 (same as the version I already had from a week ago).

Thanks.

**Comment by ldiqual** [comment]
@jb431 Thanks for reporting! Can you try resolving from the master branch, something like this:

```
github "TakeScoop/SwiftyRSA" "master"
```

I believe Carthage resolves with any tagged version when no version is specified, in this case the last version: 0.3.0. SHA2 changes are not tagged yet.

**Comment by jb431** [comment]
@ldiqual That handled it!  Thanks!!

**Comment by ldiqual** [comment]
@jb431 Sweet! Closing this issue then.
