### ISSUE TITLE
Error PublicKey base64Encoded

### ISSUE THREAD

**Issue by r9hacks** [TakeScoop/SwiftyRSA#153]
Error Domain=SwiftyRSA.SwiftyRSAError Code=14 "(null)"
The operation couldn’t be completed. (SwiftyRSA.SwiftyRSAError error 14.)

Creating new instance from PublicKey with base64Encoded gives this error.
Can any one explain the error?

**Comment by meshileya** [comment]
were you able to solve it? @r9hacks
