### ISSUE TITLE
How to extract publickey from a .cer file?

### ISSUE THREAD

**Issue by hdoria** [TakeScoop/SwiftyRSA#17]
I have a .cer file on my bundle.

```obj-c
NSString *pass = [SwiftyRSA encryptString:password publicKeyDER:publicKeyData padding:kSecPaddingPKCS1 error:nil];
```
How to extract the publicKey from a .cer file and use it?

**Comment by paulw11** [comment]
It depends on what is inside your .cer file; it can be either a binary DER format or an ascii encoded PEM format, but essentially you just need to load the contents of the file.  See https://github.com/TakeScoop/SwiftyRSA/blob/master/SwiftyRSATests/TestUtils.swift

**Comment by hdoria** [comment]
This is what I'm trying to do, but it's not working:

```objective-c
NSBundle *bundle = [NSBundle bundleForClass:self.class];
NSString *pubPath = [bundle pathForResource:@"myCertificate" ofType:@"cer"];
NSData *publicKeyData = [NSData dataWithContentsOfFile:pubPath];
NSString *password = [SwiftyRSA encryptString:@"123456" publicKeyDER:publicKeyData padding:kSecPaddingPKCS1 error:nil];
```

The app crash with EXC_BAD_ACCESS when calling the encryptString method.

There's a myCertificate.cer file on my bundle.

**Comment by paulw11** [comment]
Have you tried setting a breakpoint and stepping through the code in the debugger.  Check each step has returned non-nil.

**Comment by hdoria** [comment]
Yes, i did. 
```objective-c
NSBundle *bundle = [NSBundle bundleForClass:self.class];
NSString *pubPath = [bundle pathForResource:@"myCertificate" ofType:@"cer"];
NSData *publicKeyData = [NSData dataWithContentsOfFile:pubPath];
```

Every step until here is valid and always returned non-nil. 

The problem seems to be here:

```objective-c
 [SwiftyRSA encryptString:@"123456" publicKeyDER:publicKeyData padding:kSecPaddingPKCS1 error:nil];
```

The app crashes on stripPublicKeyHeader:

```
Invalid byte at index 18 (109) for public key header
```

I could not figure out what's wrong. The cert file I'm trying to use is attached below.

[cerfile.cer.zip](https://github.com/TakeScoop/SwiftyRSA/files/309165/cerfile.cer.zip)

Thanks.

**Comment by ldiqual** [comment]
@hdoria Would you mind giving more info on what is inside your certificate exactly? Is it a public key? What's the format and how was it produced?

**Comment by hdoria** [comment]
This is how I got the certificate:

```bash
$ echo | openssl s_client -connect mb.banese.com.br:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > cert.pem
$ openssl x509 -inform PEM -in cert.pem -outform DER -out certificate.cer
```

**Comment by ldiqual** [comment]
@hdoria Got it. What you get from this is a certificate, but SwiftyRSA only works with public and private keys. You need to extract the public key from this SSL certificate. Something like this maybe? https://stackoverflow.com/questions/17143606/how-to-save-public-key-from-a-certificate-in-pem-format

**Comment by hdoria** [comment]
My bad. Got it. Thanks. :)

**Comment by Shanlovana** [comment]
[cerfile.cer.zip](https://github.com/TakeScoop/SwiftyRSA/files/3197132/cerfile.cer.zip)
