### ISSUE TITLE
Encrypt with public key from server (string)

### ISSUE THREAD

**Issue by TulioOParreiras** [TakeScoop/SwiftyRSA#179]
Hi!

I am trying to encrypt a String using a public key that I receive from server that is also a String.
When I try to generate the public key using the class `PublicKey` I get the error `asn1ParsingFailed`.

- Version of SwiftyRSA: 1.5.0
- Code:

        let publicKey = try PublicKey(pemEncoded: pubKey)
        let clear = try ClearMessage(string: value, using: .utf8)
        let encrypted = try clear.encrypted(with: publicKey, padding: .PKCS1)
        return encrypted.base64String
    

- Error: asn1ParsingFailed
- Error description: The operation couldn’t be completed. (SwiftyRSA.SwiftyRSAError error 14.) 
- The key is a String.

Thanks!

**Comment by meshileya** [comment]
HI @TulioOParreiras , were you able to solve this?

**Comment by TulioOParreiras** [comment]
Oh I forgot to close the issue. It was a problem from the backend...
