### ISSUE TITLE
Push new version to Cocoapods

### ISSUE THREAD

**Issue by rsaarloos** [TakeScoop/SwiftyRSA#18]
As the title reads. Currently in Master branch there are improvements with regards to SHA2, but if you 'just' pull the latest known CocoaPods version (0.3.0) you will not get these improvements.

**Comment by ldiqual** [comment]
@rsaarloos Thanks for opening an issue! I will push a new version asap, will close the issue when it's done. Thanks again.

**Comment by ldiqual** [comment]
@rsaarloos I pushed SwiftyRSA 0.4.0 to the Cocoapods trunk. Let me know if you have any issue setting it up. Cheers!
