### ISSUE TITLE
Swift 5.2 ClearMessage Has Bad Encryption

### ISSUE THREAD

**Issue by saeedmozaffari** [TakeScoop/SwiftyRSA#183]
After update swift version to 5.2 and update build latest "SwiftyRSA", encryption method at "ClearMessage" class sometime has wrong data. 

Test : 
I saved a clear message when encryption was OK, and for next time used from that object again
 BUT!
for second time encrypted data was not ok. in fact correct encrypted data completely is random after update to swift 5.2.

```java
func generateEncryptedSymmetricKeyData(length :Int,secondaryChunkSize:Int) -> Data {
// TEST AGAIN: repeat 'encrypted' method when encryption was ok
        if isOk { 
            do {
                encryptedSymmetricKeyData = Data()
                for clear in safeClearMessage {
                    let encrypted = try clear.encrypted(with: publicKeyClient, padding: .PKCS1)
                    encryptedSymmetricKeyData.append(contentsOf: encrypted.data)
                }
                return encryptedSymmetricKeyData
            } catch  {
                print(error)
            }
        }
  //===================================================================


        encryptedSymmetricKeyData = Data()
        symmetricKey = IGGlobal.randomString(length: length)
        do {
            let symmetricKeyData = symmetricKey.data(using: .utf8)
            var encSymmetricKeyData = try encrypt(rawData: symmetricKeyData!) 
            let publicKey = try PublicKey(pemEncoded: embeddedPublicKey)
            publicKeyClient = publicKey
            while(0<encSymmetricKeyData.count){
                let chunk = encSymmetricKeyData.subdata(in: 0..<secondaryChunkSize)
                let clear = ClearMessage(data: chunk)

                // STORE: store "ClearMessage" Object for use next time
                safeClearMessage.append(clear)

               // **ERROR LINE** this line sometimes is OK and sometimes is NOT OK
               let encrypted = try clear.encrypted(with: publicKey, padding: .PKCS1)


                encryptedSymmetricKeyData.append(contentsOf: encrypted.data)
                encSymmetricKeyData = encSymmetricKeyData.subdata(in: secondaryChunkSize..<encSymmetricKeyData.count)
            }
        } catch  {
            print(error)
        }
        return encryptedSymmetricKeyData
    }
```

**Comment by Glaubenio** [comment]
@TakeScoop any updates on this?

**Comment by phxev** [comment]
We're facing the same problem...

**Comment by evermeer** [comment]
In our case we had about 10% of encryption failures.
Moving back to Xcode 11.3.1 'solved' the issue for me.

**Comment by jannemecek** [comment]
AFAIK this isn't specifically caused by SwiftyRSA. It seems to fail during `SecKeyEncrypt` with https://developer.apple.com/documentation/security/1542001-security_framework_result_codes/errsecparam?language=objc

I haven't found a way to reproduce this in SwiftyRSA unit tests, though it does happen fairly often in production/our app.

**Comment by otsec** [comment]
We are trying to encode credit card data and get an error every time for month, year and cvc. 

Looks like this problem can be reproduced more often if you trying to encrypt small strings. Like 2–4 symbols.

**Comment by oscar-fung** [comment]
I am experiencing the same issue after migrating my project from Xcode 10.1 to Xcode 11.4. I am asking for Apple for this. Will keep update in this post.

https://forums.developer.apple.com/message/415437#415437

**Comment by johnharutyunyan** [comment]
We encountered the same problem when trying to decrypt message.

`        do {
            debugPrint("\(Date()) Function: \(#function), Line: \(#line)")
            let encrypted = try EncryptedMessage(base64Encoded: message)
            let privateKey = try PrivateKey(pemEncoded: privateKeyString)
            let decrypted = try encrypted.decrypted(with: privateKey, padding: .PKCS1)
            let decryptedMessage = try decrypted.string(encoding: .utf8)
            
            return decryptedMessage
        } catch {
            debugPrint("\(Date()) Function: \(#function), Line: \(#line)")
            debugPrint(error.localizedDescription)
            return "Bad decryption"
        }`

Not always, but sometimes we got "Bad decryption"

**Comment by otsec** [comment]
Looks like problem is here 
https://github.com/TakeScoop/SwiftyRSA/blob/1e4ff8d3b2a78f2439910ad17594fbe008727e0a/Source/EncryptedMessage.swift#L56

It always was there, but since Swift 5.2 UnsafePointer become much more "unsafe".

**Comment by jannemecek** [comment]
Can any of you test with the fork I made recently? I didn't have time to do extensive testing, but the update fixed the warnings (by using proper `Data` initializer that's available now) and I haven't seen the bug occur. Unit tests also all seem to pass.

`pod 'SwiftyRSA', :git => 'https://github.com/jannemecek/SwiftyRSA.git', :branch => 'fix/dangling-pointers'`

**Comment by saeedmozaffari** [comment]
**Awesome Solution**
This problem is because of "ClearMessage" class. after update xCode to the latest version and update carthage, encryption sometimes was unsuccessful. 

_**Solution :**_ just copy "ClearMessage" class from swiftyRSA source in to your project with a new name and use from this class instead of "ClearMessage" at swiftyRSA.
seems to this problem is related to compile time and language version.
after than do this action this problem completely solved.

**Comment by evermeer** [comment]
@jannemecek I just did a test run (1000 api calls using RSA encryption) With your fix they all succeeded. With the original SwiftyRSA about the ½ failed. Could you make a PR for this?

**Comment by jannemecek** [comment]
Great to hear that, just opened #184

**Comment by oscar-fung** [comment]
> I am experiencing the same issue after migrating my project from Xcode 10.1 to Xcode 11.4. I am asking for Apple for this. Will keep update in this post.
> 
> https://forums.developer.apple.com/message/415437#415437

jannemecek's solution solves my issue. Thanks!

**Comment by streem-ua** [comment]
> Can any of you test with the fork I made recently? I didn't have time to do extensive testing, but the update fixed the warnings (by using proper `Data` initializer that's available now) and I haven't seen the bug occur. Unit tests also all seem to pass.
> 
> `pod 'SwiftyRSA', :git => 'https://github.com/jannemecek/SwiftyRSA.git', :branch => 'fix/dangling-pointers'`

It works. Thank you! Can you please explain, what was wrong and what your fix do? Thanks

**Comment by leoniralves** [comment]
I had the same problem, but in version 1.6.0 this has been resolved.
Now with 100% success in decryption.
