### ISSUE TITLE
SecKeyEncrypt/Decrypt still failing after Xcode 11.5

### ISSUE THREAD

**Issue by c-scalcucci** [TakeScoop/SwiftyRSA#192]
After upgrading our Xcode from 11.2 -> 11.5, SecKeyEncrypt/Decrypt seems to be failing. It won't throw any errors, but the data is clearly not right. We are encrypting 32 bytes and sending it to the backend, which decrypts it as far bigger. I have made sure to pull in #184 to fix the dangling pointers, but we are still failing pretty often. 

I'll post hex dumps later, just wondering if anyone else is still having crypto failures even after #184?

Encrypt: 
`            
if let publicKey = getPublicKey() {
    let clear = RSAClearMessage(data: key.data)
    let encrypted = try clear.encrypted(with: publicKey, padding: [])
    return encrypted.data
} `

Decrypt:
`
let encryptedMessage = RSAEncryptedMessage(data: key)
let decrypted = try encryptedMessage.decrypted(with: privateKey, padding: [])
`

**Comment by pmacro** [comment]
@c-scalcucci we don't have `RSAClearMessage` in this project.  Whatever that code is, perhaps it needs the same dangling pointer fix?
