### ISSUE TITLE
OS X Platform Support

### ISSUE THREAD

**Issue by greenantdotcom** [TakeScoop/SwiftyRSA#24]
# Problem

Currently, the APIs which this framework expose are using calls/constants/features in the Security framework which are only available on iOS/tvOS/watchOS but not macOS.

To wit, adding a macOS Target set up the same as the existing iOS one generates these initial issues:

```
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:244:26: Use of unresolved identifier 'SecKeyEncrypt'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:275:26: Use of unresolved identifier 'SecKeyDecrypt'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:651:22: Use of unresolved identifier 'SecKeyRawSign'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:737:22: Use of unresolved identifier 'SecKeyRawVerify'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:759:24: Type 'SecPadding' has no member 'PKCS1SHA224'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:762:24: Type 'SecPadding' has no member 'PKCS1SHA256'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:765:24: Type 'SecPadding' has no member 'PKCS1SHA384'
/Users/mhughes5/Repos/SwiftyRSA/SwiftyRSA/SwiftyRSA.swift:768:24: Type 'SecPadding' has no member 'PKCS1SHA512'
```

While many of these methods seem like they should be available on macOS from the documentation, they aren't. 👎

What is available, though, are a series of macOS-only APIs that do the same, even richer, operations but just using a different API set. I have a set of code I am maintaining for an internal project that does many of the same ops as SwiftyRSA but whose source code **only** works on macOS.

So, the crux of the issue:

* Adding macOS support is not a straight line
* The libraries/constants/dependencies are very different between macOS and iOS/tvOS/watchOS
* If you factor in true multi-platform support (say, Linux or FreeBSD), adding other backend libraries could lead to a lot of #if's and os() checks that would sully the readability of the code.

So what I'd like to propose is two-fold:

# Implementation Change

1. Front-end user-facing classes/protocols/enums that make up the firm public API
2. Backend crypto-lib facing classes/protocols
3. Concrete implementations of item 2

Consider the following as an example of how this would be implemented, allowing for a unified front-end, but a composable backend:

```swift
@objc public protocol SwiftyRSABackendProtocol {
    // …
}

#if os(OSX)
    public class SecTransformBackend : NSObject, SwiftyRSABackendProtocol {}
#elseif os(iOS) || os(watchOS) || os(tvOS)
    public class SecurityFrameworkBackend : NSObject, SwiftyRSABackendProtocol {}
#elseif os(Linux) || os(FreeBSD)
    public class OpenSSLBackend : NSObject, SwiftyRSABackendProtocol {}
    public class PolarSSLBackend : NSObject, SwiftyRSABackendProtocol {}
#endif

@objc public class SwiftyRSA : NSObject {
    /// Default instance for new SwiftyRSA instances
    /// TODO: This would be a swell Factory class/methods thing
    private static var defaultDriverInstance : SwiftyRSABackendProtocol {
        #if os(OSX)
            return SecTransformBackend()
        #elseif os(iOS) || os(watchOS) || os(tvOS)
            return SecurityFrameworkBackend()
        #elseif os(Linux) || os(FreeBSD)
            // Default to something…
            return OpenSSLBackend()
        #endif
    }
    
    /// Concrete instance to use for our purposes
    private var driverInstance : SwiftyRSABackendProtocol
    
    /// Initializes a new object with an instance of the default driver for this platform
    override init(){
        driverInstance = SwiftyRSA.defaultDriverInstance
    }
    
    /// Initializes a new object with the driver instance provided by the user
    @objc init(driver:SwiftyRSABackendProtocol){
        driverInstance = driver
    }
}

let rsa = SwiftyRSA() // Let the constructor use the `defaultDriverInstance` to initialize our `driverInstance` ivar

// -or-

let rsa2 = SwiftyRSA(driver: SecTransformBackend())
let rsa3 = SwiftyRSA(driver: PolarSSLBackend())
```

The purpose for the public initializer is so that as additional drivers are created by the community/project, they can be composed easily - as an example, if someone wrote a backend for, say, GnuTLS - without having to update the core `SwiftyRSA` project to support it.

# Testing Methodology

I strongly suggest a thorough test suite such that each class that implements `SwiftyRSABackendProtocol` would have to adhere to do be "valid" to be sure that a set of inputs always deliver a set of outputs, such as:

* SHA256 with input `abc` always yields exactly `ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad`
* If you have this data (…) and this key (…) and use this padding (…), your output should always be (…)

This will allow both driver implementors to know the outcome bar, but also allow consumers of both `SwiftyRSA` and those add-on drivers to have trust that the values that come out are deterministic regardless of platform or backend.

-----

What do you think?

**Comment by ldiqual** [comment]
@greenantdotcom Thanks a lot for opening an issue.

Honestly OSX support is not something I envisioned. Here's my thought process here:

 - SwiftyRSA was created to work around the iOS limitation of adding private/public keys directly without a certificate. As far as I know OSX doesn't have the same limitations, so having SwiftyRSA on OSX would at this point be purely syntactic sugar. Not that it's wrong, but it solves a different problem.
 - One of the risks of adding more features like these is that you need people to maintain them and detect bugs as they integrate with the library. We at Scoop don't have an OSX app that would make use of encryption, so maintaining it would be a lesser priority.
 - When I look the backend architecture that you propose, I'm really worried that we would transform SwiftyRSA from a small library that does one thing well, to a generic all-platform crypto library. I don't think that would work well and that we would have the resources to maintain this.

Are there other libraries that wrap the Security Transform framework for OSX? How different would the SwiftyRSA iOS/tvOS/watchOS codebase be from a SwiftyRSA OSX codebase if you were to write it from scratch? Is there actually a significant amount of common code for the two?

More generally, it seems to me that having different libraries for each platform/backend is a better solution here.

**Comment by ldiqual** [comment]
@greenantdotcom Closing this. Feel free to re-open if you want the conversation to keep going.

**Comment by reitzig** [comment]
@ldiqual  Since there is a unified API for both platforms now, this seems to be within easier reach:
https://forums.developer.apple.com/thread/51762
