### ISSUE TITLE
Bouncy Castle Encryption

### ISSUE THREAD

**Issue by rsdev-darshan** [TakeScoop/SwiftyRSA#25]
Hey, I am trying to integrate with an API which uses BouncyCastle encryption, so the server is not able to decrypt the data which i am encrypting using SwiftyRSA. 
Am i doing something wrong or it won't work because it is using Bouncy Castle?

Kindly Help.

**Comment by paulw11** [comment]
Can you provide more information?  What are you trying to do, exactly?  Are you getting any error messages?  Have you used the correct keys and the same encryption method and padding on both sides?

**Comment by rsdev-darshan** [comment]
OK, I am developing client side app, Server side API are already made and are not changeable.
And while login to the app i need to do encryption of data. The encryption used on server side is a RSA encryption using BouncyCastle Library (Java) http://www.bouncycastle.org . And this lib only supports Java and C#. I am using SwiftyRSA to encrypt the data, but the server is not able to decrypt the data. i guess because of different encryption method. so what can be done?

Please help.
Thanks.

**Comment by paulw11** [comment]
Without more information nothing.  Can you get any error messages from the server side?  Can you show the code you are using with SwiftyRSA to encrypt the data?

**Comment by rsdev-darshan** [comment]
In first request, Client will get base64 encoded Public key1 from server. Client needs to decode it. Generate a pair of key ie. Public2/Private2 and send Public key 2 to server in the second request by encrypting it using decoded Public Key1 (i am doing this using func encryptString of SwiftyRSA) and along with this client needs to send SHA 256 hashed decoded Public key1(in string format) to server.

let encryptedString = try! rsa.encryptString(pk, publicKey: pk1 as! SecKey, padding: .PKCS1)
pk1 - base64 decoded publickey1 from server
pk - publicKey generated by me

Error - Server is not able to decrypt the public key that i am sending, he is getting an error, "Data should start with zero, bad padding"

**Comment by paulw11** [comment]
If you decrypt the result of `encryptString` using your private key do you get the right result?  Are you base64 encoding the result of `encryptString` before you send it to the server?

**Comment by rsdev-darshan** [comment]
Yes, i am getting the right result on decryption.
No, i am not base64 encoding the result of encryptString. i guess encryptString return a base64 encoded string.

**Comment by paulw11** [comment]
From searching it seems that "Data should start with zero, bad padding" indicates a key pair mismatch; the private key that is being used to decrypt the data is different.  If you save your base64 encoded ciphertext to a text file then you should be able to use the following command line in OS X to decrypt it `cat ciphertext | base64 -D | openssl rsautl -decrypt -inkey privatekey.pem -out plaintext` where privatekey.pem is the private key that corresponds to the public key that was used to encrypt in PEM format

**Comment by rsdev-darshan** [comment]
I got it working, made a few changes in encryptData func according to the BouncyCastle Encryption.

Thanks.

**Comment by ldiqual** [comment]
@rsdev-darshan Glad it's working for you. Can you elaborate on what you changed exactly and on whether it would be worth having in SwiftyRSA?

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by rsdev-darshan** [comment]
I have made changed according to the BouncyCastle Encryption. I had a look at how they are encrypting and followed it.

But am not yet done, encryption was successful but decryption is yet to be done. In short, I am still stuck.

**Comment by dimonmykytenko** [comment]
Hey, rsdev-darshan. You found a way to decrypt for BouncyCastle ?
