### ISSUE TITLE
I need methods

### ISSUE THREAD

**Issue by hejunbinlan** [TakeScoop/SwiftyRSA#26]
encryptString(str, privateKeyPEM: pemString)
decryptString(str, publicKeyPEM: pemString)

**Comment by paulw11** [comment]
You don't encrypt data with a private key or decrypt data with a public key.  You can sign data with a private key and then verify that signature with the public key using `let signatureString = try! SwiftyRSA.signString(str, privateKeyPEM: pemString)` and `let verificationResult = try! SwiftyRSA.verifySignatureString(str, signature: sigString, publicKeyPEM: pemString)`

**Comment by FXLynn** [comment]
i need too...
