### ISSUE TITLE
Get public key form a .der file raise an error

### ISSUE THREAD

**Issue by LvJianting** [TakeScoop/SwiftyRSA#28]
I have generate a .der file with openssl, but it raise an error when I do unit test(the .pem file which generate this .der file can work well). This is the error information:
fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.takescoop.SwiftyRSA Code=500 "Invalid byte at index 18 (22) for public key header" UserInfo={NSLocalizedDescription=Invalid byte at index 18 (22) for public key header}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54

I have thought I generate a wrong .der file,but it works well when I tested with another framework(https://github.com/adow/SecrecySwift) which can only use .der file and PKCS1Padding, it passed. So if I generate the .der file with incorrectly way, or there is some issues when use .der file to get public key?
PS: My English isn't well, if I describe something as ambiguous, I will be sorry.

**Comment by ldiqual** [comment]
@LvJianting Thanks for opening an issue! Can you generate another PEM/DER key that would fail processing in SwiftyRSA and share it in this issue? It would make investigating a lot easier.

**Comment by LvJianting** [comment]
@ldiqual I'm sorry so long to restore you, here is PEM/DER file, the PEM file success, but DER file fail . The following way is the example that I generate these files:
openssl genrsa  -out private.pem  2048
openssl rsa  -pubout  -in private.pem  -out public.pem
openssl req -new -key private.pem -out cert.csr
openssl x509 -req -days 3650 -in cert.csr -signkey private.pem -out cert.crt
openssl x509 -outform der -in cert.crt -out cert.der
openssl pkcs12 -export -inkey private.pem -in cert.crt -out cert.p12

[rsa_key.zip](https://github.com/TakeScoop/SwiftyRSA/files/448932/rsa_key.zip)

**Comment by ldiqual** [comment]
@LvJianting Sorry for the delay on this. I didn't try to use your keys with SwiftyRSA quite yet, but one thing I notice is that your DER file is not a *key*, it is a *certificate*. SwiftyRSA doesn't support certificates, only keys. Does that make sense?

**Comment by ldiqual** [comment]
@LvJianting I'm closing this since I believe it is indeed a certificate issue. Let me know if you need to reopen.
