### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by TofPlay** [TakeScoop/SwiftyRSA#3]
It's will be great to add [Carthage](https://www.raywenderlich.com/109330/carthage-tutorial-getting-started) support
You can follow this tutorial: [Making Carthage-compatible Frameworks with Swift](http://blog.mat.tc/how-to-make-a-carthage-compatible-framework/)

**Comment by ldiqual** [comment]
@TofPlay Thanks for your suggestion! From your second link, it seems that all we'd have to do is share the SwiftRSA framework scheme? Everything else is tagged and pushed to Github.
Also, if we were to add that, I'd like to add CI tests to make sure everything works fine with every upgrade. Do you have an example of a project that is Carthage compatible and tests the Carthage integration on Circle or Travis?
