### ISSUE TITLE
Error while decripting

### ISSUE THREAD

**Issue by lu1sprz** [TakeScoop/SwiftyRSA#30]
Hi, im using your hub to encrypt and everything works like charm, but decrypt doesn't work, throws me this error : Error Domain=com.takescoop.SwiftyRSA Code=500 "Couldn't get key reference from the keychain" UserInfo={NSLocalizedDescription=Couldn't get key reference from the keychain}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54, can you help me ?

**Comment by ashishguru1986** [comment]
I am facing same issue

**Comment by paulw11** [comment]
Can you share some code?  How are you loading the private key into the keychain?

**Comment by ashishguru1986** [comment]
Issue is fixed after changing key.

**Comment by ldiqual** [comment]
Thanks for getting back to us! Closing now

**Comment by ihs-Sharma** [comment]
> Issue is fixed after changing key.
Hi @ashishguru1986, can you please help me in this same I'm getting "Couldn't get key reference from the keychain".

Please help
