### ISSUE TITLE
Unable to Decrypt : Couldn't convert decrypted data to UTF8 string

### ISSUE THREAD

**Issue by ashishguru1986** [TakeScoop/SwiftyRSA#31]
I am trying to decrypt a string encrypted by node crypto .

Error: 

fatal error: 'try!' expression unexpectedly raised an error: Error Domain=com.takescoop.SwiftyRSA Code=500 "Couldn't convert decrypted data to UTF8 string" UserInfo={NSLocalizedDescription=Couldn't convert decrypted data to UTF8 string}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54

==================Code ====================
      
/-------Able to get decryptedData bytes but utf-8 conversion fails------/
let decryptedData = try decryptData(data, privateKey: privateKey, padding: padding)

        guard let decryptedString = NSString(data: decryptedData, encoding: NSUTF8StringEncoding) else {
            throw SwiftyRSAError(message: "Couldn't convert decrypted data to UTF8 string")
        }

**Comment by ldiqual** [comment]
@ashishguru1986 Thanks for opening an issue. Can you share the encrypted data + private key you're using?

**Comment by ashishguru1986** [comment]
**UnEncrypted Text**: "ABCDEF:56779b084e47:af83b58044be0c86563bc0d4aec0b315:A2B2"

**For encryption node.js crypto is used :**   
let encrypt = crypto.publicEncrypt(publicKey, buff); // Node.js code

**EncryptedText** : "i//vu49WNmg/OcXTr9J7D7F7u6yDFNAIIsBDlFxIQ0velOytcmHB5dVC11o9na5/lyoHKuqhEUB91ld44R/WmBJPIbu1I8prXI6IVnK/K/ESa1jbkmqzfd4DW/pADeA9DV83V8p5nD7m8DhXUUc4R9cRqKjD/B/b5W74rS/712XpEkIB58qVs4y3aw/sGW938ifATv6DMIR4KJghAhKP+LBWIbyo5avCsH3xTnsxP3z9CdpmVRKOUbL9qfuq42tSmsXWaMWMQrD88bJyKBiz96rfMuONIVLO/Rm8RVYSEN7zZaObFXHcV6k07tvU/uJqcWFd90x4uAQFbzyFXd9vsA=="

**Swift code to decrypt:**

        //Decrypt------
        let enToken = "i//vu49WNmg/OcXTr9J7D7F7u6yDFNAIIsBDlFxIQ0velOytcmHB5dVC11o9na5/lyoHKuqhEUB91ld44R/WmBJPIbu1I8prXI6IVnK/K/ESa1jbkmqzfd4DW/pADeA9DV83V8p5nD7m8DhXUUc4R9cRqKjD/B/b5W74rS/712XpEkIB58qVs4y3aw/sGW938ifATv6DMIR4KJghAhKP+LBWIbyo5avCsH3xTnsxP3z9CdpmVRKOUbL9qfuq42tSmsXWaMWMQrD88bJyKBiz96rfMuONIVLO/Rm8RVYSEN7zZaObFXHcV6k07tvU/uJqcWFd90x4uAQFbzyFXd9vsA=="
        
        let privPath   = NSBundle.mainBundle().pathForResource("private", ofType: "pem")
        let privPEM = try! NSString(contentsOfURL: NSURL(fileURLWithPath: privPath!), encoding: NSUTF8StringEncoding) as String
        let privKey    = try! rsa.privateKeyFromPEMString(privPEM)
        
        let decryptedString = try! rsa.decryptString(enToken, privateKey: privKey)
        print("Deecrypted String :", decryptedString)
        //-------

 private and public keys are attached.

[RSA-Keys.zip](https://github.com/TakeScoop/SwiftyRSA/files/471293/RSA-Keys.zip)

**Comment by ldiqual** [comment]
@ashishguru1986 Thanks for the details, will look into it. In the meantime, I'd suggest to play around with the padding that you provide to `decryptString` because I believe node's crypto module uses a different default padding than SwiftyRSA's (PKCS1).

**Comment by ashishguru1986** [comment]
Thanks.
Changed padding to .OAEP , it worked :)

**Comment by Darren120** [comment]
@ashishguru1986 @ldiqual  Hey would you two mind explaining why using OAEP padding on swiftyRSA work? I import public key to NodeJS via JSON with padding 'pkcs1-public', then send the encrypted message via base64 back to client and works with decrypted via OAEP but if I use .pkcs1 for swiftyRSA it throws error?
