### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by hdoria** [TakeScoop/SwiftyRSA#33]
Any plans for Swift 3.0?

**Comment by ldiqual** [comment]
@hdoria Hey there, thanks for opening an issue. There's a `swift-3.0` branch that handles swift 3 + iOS 10. I'll release a new version when it's completely ready (ie: when methods are renamed correctly). Thanks for jumping in!

**Comment by lztetreault** [comment]
When we attempt to build the swift 3 branch on Xcode 8.0 we get around 70 errors. Is the branch currently working for you or do you still have issues?

**Comment by sadaf-behbahani** [comment]
Hi there , I still have this issue , I am using swift 3.1 and my xCode version is 8.3.1. After I did "pod install". I get about 50 errors. Has this issue been solved ?
