### ISSUE TITLE
Current pod 0.5.0 doesn't build under ios10/xcode8 - it fails in legacy mode

### ISSUE THREAD

**Issue by Daij-Djan** [TakeScoop/SwiftyRSA#37]
Current pod 0.5.0 doesn't build under ios10/xcode8

-- Im not talking about swift 3 support :D I mean: it fails in legacy mode

**Comment by ldiqual** [comment]
@Daij-Djan SwiftRSA doesn't support Swift 2.3. Is that what you're referring to?

**Comment by Daij-Djan** [comment]
well 0.4.0 works fine in xcode8 legacy mode ;)
0.5.0 broke it — I haven’t analyzed it

LG
Dominik

Web: https://pich.info
Twitter: @DaijDjan
Facebook: Dominik.Pich

**Comment by ldiqual** [comment]
@Daij-Djan You're right, SwiftyRSA won't build in legacy mode because it doesn't support Swift 2.3. https://github.com/TakeScoop/SwiftyRSA/pull/32 might address the issue. Closing this in favor of https://github.com/TakeScoop/SwiftyRSA/issues/38
