### ISSUE TITLE
RSA publicKey String

### ISSUE THREAD

**Issue by Adarkas2302** [TakeScoop/SwiftyRSA#39]
Is it possible to get the public key in PEM String format with SwiftyRSA, or is using the CryptoExportImportManager still the best option?
Because i can't get the Manager to work in Swift 3.0.

**Comment by ldiqual** [comment]
@Adarkas2302 It's not possible to export a key to PEM in SwiftyRSA yet. To be honest it wasn't on my schedule but I think it's a simple enough feature. Will think about it.

**Comment by Adarkas2302** [comment]
Thanks, would make my life easier. I have enough to change in all my apps ;).

**Comment by Adarkas2302** [comment]
Got it working myself, but now i have to export my key in DER format as Data. Well lets see i can manage that to.
