### ISSUE TITLE
Swift 3.0 bundle.path(forResource) returns nil

### ISSUE THREAD

**Issue by Komak57** [TakeScoop/SwiftyRSA#42]
Need to generate a public and private key for the lifetime of the device. Gone several paths before finally ending up in SwiftyRSA. Initial device is iOS 8.3 (target 8.0) in XCODE8.

// Public key (PEM)
if let pubPath     = bundle.path(forResource: "public", ofType: "pem") {
	let pubString  = try String(contentsOfFile: pubPath, encoding: String.Encoding.utf8)
	self.PublicKey = try rsa.publicKeyFromPEMString(pubString)
} else {
	print("Unable to generate Public Key")
}

pubPath always returns nil

**Comment by greenantdotcom** [comment]
@Komak57

This is likely not a SwiftyRSA specific issue, and likely more one related to whether the resource you are expecting (`public.pem`) is being properly copied to the `bundle`'s resource path at build time.

I tested a new app using Xcode 8, added a `public.pem` file, and it worked as expected:

```swift
//
//  ViewController.swift
//  PEM Loader
//
//  Created by Mark Hughes on 10/8/16.
//  Copyright © 2016 Mark Hughes. All rights reserved.
//

import UIKit

class ViewController: UIViewController {
    @IBOutlet weak var textLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let bundle = Bundle(for: ViewController.self)
        
        let goodPath = bundle.path(forResource:"public", ofType:"pem")
        let badPath = bundle.path(forResource: "public2", ofType: "pem")
        
        textLabel.text = (goodPath != nil) ? "😇" : "😡"
```

Please check your build's `Build Phases` > `Copy Bundle Resources` to ensure your PEM file is being copied over.

**Comment by Komak57** [comment]
Confirmed. I had yet to realize that this framework did not generate the public or private keys, only provided handles to interact with them. Also, this library refuses to work with a simulator. Not extremely vital, as I have a device to test and tinker with, and Simulators aren't always accurate, but it could be something to look into later.
