### ISSUE TITLE
encrypted data is null.

### ISSUE THREAD

**Issue by suniliphone** [TakeScoop/SwiftyRSA#43]
![screen shot 2016-10-10 at 10 41 54 am](https://cloud.githubusercontent.com/assets/6223169/19227384/537638f6-8ed6-11e6-8026-2eb04b0e4547.png)

Hi,
Please find attached screenshot and could you please tell me why i am getting nil value here.

**Comment by paulw11** [comment]
Your code is attempting to sign data, so you need to use a private key.  You can encrypt data with a public key by calling `encryptData(data, publicKeyPEM:)`

**Comment by paulw11** [comment]
Have you confirmed that `data` isn't nil or empty?. What value do you get for `error` ?

**Comment by suniliphone** [comment]
Hi paulw11,

I printed in log "The operation couldn’t be completed. (com.takescoop.SwiftyRSA error 500.)"

**Comment by paulw11** [comment]
You have two problems:

1. You are passing `pubPath` instead of `pubString` to the encrypt function
2. Your `pubString` contains a certificate, not a public key.  

Once I fixed the first problem and extracted the public key from your certificate your code worked.

You can extract the public key using 
`openssl x509 -pubkey -noout -in certificate.pem  > pubkey.pem` in a terminal

You need to change your code to refer to `pubkey.pem` rather than `certificate.pem`

**Comment by suniliphone** [comment]
![screen shot 2016-10-10 at 1 15 34 pm](https://cloud.githubusercontent.com/assets/6223169/19229513/c6a971ca-8eeb-11e6-824d-d9049e7b5ee9.png)
[SignatureDemo 2.zip](https://github.com/TakeScoop/SwiftyRSA/files/518973/SignatureDemo.2.zip)

HI paulw11,

I changed the code as per your points still i am getting nil value. Could you please check while a min..

**Comment by paulw11** [comment]
When I tested it before it was on a machine with Xcode 7 and it worked.  Testing it on Xcode 8 I get the same problem as you.

**Comment by paulw11** [comment]
You need to use version 0.5.0 with Xcode 8 - I changed your pod file as follows:
platform :ios, '10.0'
target 'SignatureDemo' do
 pod 'SwiftyRSA', '~> 0.5.0'
end 
use_frameworks!

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end 
end

and it worked.

**Comment by suniliphone** [comment]
Hello paulw11,

Thanks a lot paulw11 its working fine, May i get your email id or skype id.
