### ISSUE TITLE
How to embed signature into pdf for ios

### ISSUE THREAD

**Issue by Naresh123321** [TakeScoop/SwiftyRSA#44]
Dear all,

I have successfully generated the signature value (pkcs7 data) with swiftRSA. Now i want to embed that signature into pdf can one  please tell me how to achive this in ios or share me if you have any demo code.

I am student of jagans engineering college, working on my sem project...

Thanks & Regards,
Naresh.

**Comment by ldiqual** [comment]
@Naresh123321 Thanks for opening an issue! SwiftyRSA only aims at solving the Signature/Verification part, but adding this signature to a PDF is outside of the scope of the library. I would suggest looking into PSPDFKit which provides a way to add RSA/256 signature into PDFs on iOS: https://pspdfkit.com/guides/ios/current/features/digital-signatures/?search=signature. Thanks and have a great day!
