### ISSUE TITLE
Swift 3 .ignoreUnknownCharacters

### ISSUE THREAD

**Issue by halcho** [TakeScoop/SwiftyRSA#46]
Hello,

This project has been very helpful. I recently upgraded to Swift 3, and I encountered an interesting issue. I found out that there is a slight difference in behavior due to no longer specifying to ignore unknown characters in the dataFromPEMKey function. I was able to get my app to work by adding the .ignoreUnknownCharacters option:

`let keyData = Data(base64Encoded: base64EncodedKey, options: [.ignoreUnknownCharacters])`

Thank you.

**Comment by ldiqual** [comment]
@halcho Just pushed a fix in master. Would you mind giving it a try with:

```
pod 'SwiftyRSA', :git => 'git@github.com:TakeScoop/SwiftyRSA.git', :branch => 'master'
```

and let me know if it fixes your issue? Thank you!
