### ISSUE TITLE
Allow creating public/private keys from SecKey directly

### ISSUE THREAD

**Issue by ldiqual** [TakeScoop/SwiftyRSA#48]
As suggested by @rsaarloos in https://github.com/TakeScoop/SwiftyRSA/issues/47#issuecomment-257149203

**Comment by serieuxchat** [comment]
+1. I would also be interested in this enhancement.
OR at least make it an open class, so that people could write extensions for it.

**Comment by ldiqual** [comment]
@wuf810 @serieuxchat Agreed, this is something we've missed when implementing the new architecture. The main issue right now is that `PublicKey` and `PrivateKey` require a `data` field which cannot be provided if initting from a seckey, so it's not a trivial feature which would just add an initializer. Will look at it asap. Thanks for your patience!

**Comment by ldiqual** [comment]
@wuf810 @serieuxchat I added support for creating a Public/PrivateKey with a reference here: https://github.com/TakeScoop/SwiftyRSA/pull/61. Feel free to jump in if you have comments!

**Comment by wuf810** [comment]
Thanks @ldiqual  very much appreciated. Changes look good and I think that now covers all required use cases.

**Comment by wuf810** [comment]
Hi @ldiqual 

The changes look great. Any idea when you might release a new version with these changes (cocoa pods specifically)

**Comment by ldiqual** [comment]
@wuf810 Thanks for the followup! I was waiting on our other maintainers to jump in but given the delay I'll have to put someone from Scoop on it. Will get back to you soon on this. Thanks for your patience!

**Comment by shaahin** [comment]
Really nice change @ldiqual ! looking forward for this change to release :]
