### ISSUE TITLE
Get public key from .DER file

### ISSUE THREAD

**Issue by hdoria** [TakeScoop/SwiftyRSA#52]
I just upgraded SwiftyRSA and now I'm using the code from the master branch. I'm trying to get the public key from a .der file that existis on the main bundle. Here's what I'm trying to do:

```
PublicKey *pubKey = [[PublicKey alloc] initWithDerNamed:@"certfile443" in:[NSBundle mainBundle] error:&error];
NSLog(@"key: %@ - %@", pubKey, error);
```

pubKey is always null. What am I doing wrong?

**Comment by ldiqual** [comment]
@hdoria Thanks for opening an issue! What's the content of `error`?

**Comment by hdoria** [comment]
key: (null) - Error Domain=SwiftyRSA.SwiftyRSAError Code=1 "(null)"

**Comment by hdoria** [comment]
I've created a pre Swift project and now I can see the full error:

SwiftyRSAError(message: "Invalid byte at index 18 (51) for public key header"): file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178

The certificate is below. What am I missing?

[certificado.der.zip](https://github.com/TakeScoop/SwiftyRSA/files/712871/certificado.der.zip)

**Comment by ldiqual** [comment]
@hdoria Got it, you're trying to load a certificate as opposed to a public/private key. To fix this, you'll need to extract the public key with openssl:

```
openssl x509 -pubkey -noout -in cert.pem  > pubkey.pem
```

See http://stackoverflow.com/questions/17143606/how-to-save-public-key-from-a-certificate-in-pem-format

Eventually we might want to add public key extraction from a certificate.

**Comment by mattbarker016** [comment]
I'm still having trouble getting my .der file to be a valid Public Key. How could you do the above command with a .der file, I'm not having any luck. Or better yet, how can I just get the .der file to work in the constructor. I tried both with and without the Bundle parameter (I just used Bundle.main)

**Comment by ldiqual** [comment]
@mattbarker016 Any chance you could share this DER file here?

**Comment by mattbarker016** [comment]
I think I resolved my issue, can you see if it checks out? It's a closed issue from today, July 21.
