### ISSUE TITLE
Is it correct to use MemoryLayout.size?

### ISSUE THREAD

**Issue by lolgear** [TakeScoop/SwiftyRSA#58]
In SwiftyRSA.addKey
```swift
let sizeInBits = keyData.count * MemoryLayout<UInt8>.size
            let keyDict: [CFString: Any] = [
                kSecAttrKeyType: kSecAttrKeyTypeRSA,
                kSecAttrKeyClass: keyClass,
                kSecAttrKeySizeInBits: NSNumber(value: sizeInBits)
            ]
```
`keyData.count` returns count of `bytes`.
`MemoryLayout<UInt8>.size` returns count of `bytes` per UInt8 object ( 8 bits = 1 byte ). So, it returns 1 byte.

```
keyData.count * MemoryLayout<UInt8>.size = (count of bytes in keyData) * (bytes per UInt8) = count * 1 byte = count of bytes in whole keyData object.
```

So,
```
sizeOfBits != count of bits in keyData.
```

Is it correct?

**Comment by ldiqual** [comment]
@lolgear Thank you so much for pointing this out! I've fixed the issues and ran all tests, they pass correctly. I believe `SecKeyCreateWithData` ignores this key since all tests pass anyway with the wrong size, but better have correct code there. Thanks again!
