### ISSUE TITLE
Buil fails when used with Carthage "swiftlint: No such file or directory"

### ISSUE THREAD

**Issue by sam2000** [TakeScoop/SwiftyRSA#65]
When using this with Carthage the build fails with the following error in the log
/Carthage/Checkouts/SwiftyRSA/Pods/SwiftLint/swiftlint: No such file or directory
using version 1.0.0 (with locally installed swiftlint) builds fine

**Comment by ldiqual** [comment]
@sam2000 Just fixed this in `1.1.1`, thanks for reporting!

**Comment by sam2000** [comment]
Thanks very much for the prompt fix @ldiqual! Have a nice day!

**Comment by PankajNaik** [comment]
so does that mean that SwiftLint library exit for carthage ?
