### ISSUE TITLE
Issue with iOS 9.2

### ISSUE THREAD

**Issue by rishbaranwal** [TakeScoop/SwiftyRSA#67]
Hey Iqbal,

The code written for iOS 9 in add key method is not working:

            let keyCopyDict: [CFString: AnyObject] = [
                kSecClass: kSecClassKey,
                kSecAttrApplicationTag: tagData,
                kSecAttrKeyType: kSecAttrKeyTypeRSA,
                kSecAttrKeyClass: keyClass,
                kSecAttrAccessible: kSecAttrAccessibleWhenUnlocked,
                kSecReturnRef: NSNumber(bool: true),
            ]
            
            // Now fetch the SecKeyRef version of the key
            var keyRef: AnyObject? = nil
            **secStatus = SecItemCopyMatching(keyCopyDict as CFDictionary, &keyRef)**
            
            guard let unwrappedKeyRef = keyRef else {
                throw SwiftyRSAError(message: "Couldn't get key reference from the keychain")
            }

**Here, keyRef is returning nil.**

**Comment by ldiqual** [comment]
@rishbaranwal Thanks for opening an issue! Would you mind linking me to the key that you're trying to add, as well as the code you're running to create the key?

**Comment by ldiqual** [comment]
I highly suspect that your issue will be fixed with https://github.com/TakeScoop/SwiftyRSA/issues/71. Please me know if that's not the case and I'll reopen this. Thanks again!
