### ISSUE TITLE
Add status code error when throw SwiftyRSAError

### ISSUE THREAD

**Issue by xandros6** [TakeScoop/SwiftyRSA#68]
When a  SwiftyRSAError is throw the message with the exception not include the error code of SecKeyDecrypt, so debugging is difficult.

**Comment by ldiqual** [comment]
@xandros6 Thanks a lot for opening an issue! I converted SwiftyRSAError from a class to an enum so it can be introspected. Check out the `master` branch with cocoapods and let me know if it works for you!
