### ISSUE TITLE
Got an error Couldn't convert base 64 encoded string

### ISSUE THREAD

**Issue by Alwin-Lazar** [TakeScoop/SwiftyRSA#73]
```swift
public convenience init(base64Encoded base64String: String) throws {
    guard let data = Data(base64Encoded: base64String) else {
        throw SwiftyRSAError(message: "Couldn't convert base 64 encoded string ")
    }
    self.init(data: data)
}
```

I pass base64String as:

```
eVkLcBLdz/dgRdELtOQ8QYkMwRqYVoxQ2nC1PjlWmeqiAMbLGeWk1KiYmMXD1T4ekQfXI7iAaoOi
```

I don't know why this func throws.

**Comment by ldiqual** [comment]
@Alwin-Lazar thanks for opening an issue! Can you show me which code you're running (I'm mostly interested in whether you want to create a key or a message/signature)? Also, where does this base64 string come from?

**Comment by Alwin-Lazar** [comment]
@ldiqual I use publickey.pem to encrypt
encryption is successfully placed and I post that to server
server decrypted using privatekey.pem
and server return a response, that encrypted with another client_publickey.pem
I get in the format of base64 string
but when I use that base64 string to decrypt in my project it rise an error as "Couldn't convert base 64 encoded string"
python (django) is the backend
how to solve this issue

**Comment by ldiqual** [comment]
@Alwin-Lazar Would you mind sharing the backend code that you use to generate the base64 string? The actual code please. Are you sure you're encoding/decoding it using the right charset?

**Comment by Alwin-Lazar** [comment]
I will send that tomorrow I am not now in office. I think he use pycrypto Library in python

**Comment by ldiqual** [comment]
@Alwin-Lazar Bump
