### ISSUE TITLE
pod 'SwiftyRSA' ,why is the version 0.3.0 . where is the version 1.2.0?

### ISSUE THREAD

**Issue by zhangjunjiecq** [TakeScoop/SwiftyRSA#76]
Using SwiftyRSA (0.3.0)
my deployment target is 8.0. 
what's the minimun support system for version 1.2.0

**Comment by zhangjunjiecq** [comment]
I find "s.ios.deployment_target = "8.3""    Can you support system 8.0+?

**Comment by ldiqual** [comment]
We have no plans to support 8.0-8.2, as discussed here: https://github.com/TakeScoop/SwiftyRSA/issues/19. Closing this.
