### ISSUE TITLE
The operation couldn’t be completed. (SwiftyRSA.SwiftyRSAError error 1.)

### ISSUE THREAD

**Issue by 4taras4** [TakeScoop/SwiftyRSA#78]
error when I tried to use rsa public key

**Comment by anirudhamahale** [comment]
Did you found a solution for this because am getting the same?

**Comment by 4taras4** [comment]
Unfortunately no

**Comment by skram** [comment]
anything on this?

**Comment by ldiqual** [comment]
Closing this because SwiftyRSA now provides a set of errors that can be introspected, which will facilitate reporting issues like these. Please open a new issue with the keys and data that you're using, as well as the exact error that you're getting. Thanks a lot!
