### ISSUE TITLE
Add Swift 4 support

### ISSUE THREAD

**Issue by marwan87** [TakeScoop/SwiftyRSA#82]
do we know when Xcode 9 will be supported?

**Comment by ldiqual** [comment]
@marwan87 Do you mean Swift 4 support? I believe that our code is already Swift 3.2 compatible. Swift 4 support is something we need to look into a bit more.

**Comment by marwan87** [comment]
@ldiqual yes sorry I meant swift 4. do you know when you will have time? 
I will try to help where possible, I will try to create a PR
Thanks you for the update.

**Comment by codedbypm** [comment]
I created a PR for a fix on the swift4 branch. Besides that, the project compiles under XCode 9 beta 6

**Comment by ldiqual** [comment]
Swift 4 support is available here: https://github.com/TakeScoop/SwiftyRSA/tree/swift4. In the future we'll merge both branches into one with a bunch of compiler flags

**Comment by marwan87** [comment]
you guys are awesome, thanks it was on my list of this to do this week

**Comment by wasa1234** [comment]
What is the current state of play?

**Comment by ldiqual** [comment]
3.2/4.0 officially supported as of `1.3.0`. Check it out!
