### ISSUE TITLE
Xcode 9.1: 'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by razvandub** [TakeScoop/SwiftyRSA#95]
SwiftRSA 1.3.0 builds with a few compiler warnings - "'characters' is deprecated: Please use String or Substring directly".

**Comment by QianJiaming** [comment]
Hello, I deleted the 'character' keyword and recompile the project, and the warning disappeared. I hope I can help you

**Comment by razvandub** [comment]
Hello @QianJiaming, yes, sure but we need a release. Thanks.

**Comment by razvandub** [comment]
Any chance this fix will be released soon? Thanks.

**Comment by jimidobson** [comment]
Seconding this please, the deprecation warnings are cluttering the build log :)

**Comment by J7mbo** [comment]
Also have the same issue. Would you accept a PR fixing this? It should be a super small one regardless.

**Comment by ldiqual** [comment]
Just released SwiftyRSA 1.3.1 that fixes those Xcode 9.1/9.2 warnings. Thanks for your patience!

**Comment by J7mbo** [comment]
@ldiqual Many thanks for helping us!

**Comment by anirudhamahale** [comment]
Runnin pod install for pod 'SwiftyRSA' gives the version 1.3.0
putting pod 'SwiftyRSA', '1.3.1' gives 
CocoaPods could not find compatible versions for pod "SwiftyRSA":
  In Podfile:
    SwiftyRSA (= 1.3.1)
