### ISSUE TITLE
App Store Ecryption

### ISSUE THREAD

**Issue by anirudhamahale** [TakeScoop/SwiftyRSA#97]
First of all thanks alot for the great library!
I had made app using this library and I just wanted to know whether which options to select during the during the question is asked about the security. Whether to select yes or no.

**Comment by ldiqual** [comment]
NAL. In short: it depends on your use case.

SwiftyRSA does use RSA encryption and whether you need an ERN depends on what you're encrypting. I would suggest to read the iTunes Connect FAQ and get more info on applicable exemptions:

 - https://itunespartner.apple.com/en/apps/faq/Managing%20Your%20Apps_Export%20Compliance#56254694
 - https://bis.doc.gov/index.php/policy-guidance/encryption
 - https://pupeno.com/2015/12/15/legally-submit-app-apples-app-store-uses-encryption-obtain-ern/

Scoop and SwiftyRSA maintainers will not be able to give you advice on how to answer those questions. Let us know if you need anything else!
