### ISSUE TITLE
Incorrect maxChunkSize for OAEP padding

### ISSUE THREAD

**Issue by nickneiman** [TakeScoop/SwiftyRSA#98]
Hi! 

We're interested in user your library in one of our projects but we're having a little trouble with your encrypt method. When using PKCS1 padding everything works fine but when switching over to OAEP we get an error. Looking at [your code](https://github.com/TakeScoop/SwiftyRSA/blob/master/SwiftyRSA/ClearMessage.swift#L59) it seems like you might be miscalculating the "chunk size" for OAEP padding. My reading of the [OAEP spec](https://tools.ietf.org/html/rfc8017#section-7.1) is that this should actually be `blockSize - 42` assuming that the RSA hash method is outputting a 160 bit digest.

Thanks!
Nick

**Comment by nickneiman** [comment]
I've put up a PR here: https://github.com/TakeScoop/SwiftyRSA/pull/99

**Comment by ldiqual** [comment]
Fixed in https://github.com/TakeScoop/SwiftyRSA/pull/99
